name: 'Action 004'
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  print-secret:
    if: github.repository == 'typelogic/test-github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo "*** [$MY_SECRET] ***"
        env:
          MY_SECRET: ${{ secrets.my_secret }}
