name: 'Action 004'
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  print-secret:
    if: github.repository == 'typelogic/test-github-actions'
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: [ ! -z "$MY_SECRET" ] && echo "MY_SECRET=[$MY_SECRET]" || echo "MY_SECRET=undefined"
        env:
          MY_SECRET: ${{ secrets.mysecret }}
