name: 'Action 001'
on:
  schedule:
    - cron: '* * * * *' # every minute

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        if: env.DOIT != null
        run: echo "*** Doing it ***"
        env:
          DOIT: ${{ secrets.doit }}
