name: 'Delete old artifacts'
on:
  schedule:
    - cron: '* * * * *' # every minute

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      if: env.ACCESS_TOKEN != null
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.access_token }}
          expire-in: 2days # Setting this to 0 will delete all artifacts
        env:
          ACCESS_TOKEN: ${{ secrets.access_token }}
